#!/bin/bash
# Increase the master volume

LINEIN=`/usr/local/minerva/bin/mixer default get linein`
/usr/local/minerva/bin/mixer default inc master 10
/usr/local/minerva/bin/mixer default set linein $LINEIN

